name: parse-domain-test

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3.1.1
        with:
          node-version: '14.17.3'
      - run: yarn
      - run: yarn run ts-node --transpile-only test.ts
